### ISSUE TITLE
Add TypeScript files decompilation (.vts_c)

### ISSUE THREAD

**Issue by SanctusAnimus** [ValveResourceFormat/ValveResourceFormat#612]
### Is your feature request related to a problem? Please describe.

Valve seem to shift it's Panorama scripts towards typescript, would be cool to be able to decompile them as well
Right now when attempted, following error pops:
```
File: panorama\scripts\dashboard_background_loadout_treasure.vts_c (parent: E:\Apps\Steam\steamapps\common\dota 2 beta\game\dota\pak01)
System.ArgumentException: Unrecognized block type 'STAT'
   at ValveResourceFormat.Resource.ConstructFromType(String input) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 393
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 192
   at Decompiler.Decompiler.DumpVPK(String parentPath, Package package, String type, Dictionary`2 manifestData) in D:\a\ValveResourceFormat\ValveResourceFormat\Decompiler\Decompiler.cs:line 904
   ```

**Comment by SanctusAnimus** [comment]
Using CLI, `VRF Version: 5.0.2120+5859d5e3f2c412fa89f96fa9bf1ae2585e65a4ee`, `Runtime: .NET 6.0.21` on Win10, if that matters

**Comment by kristiker** [comment]
Latest build should have support for the STAT block. Ref: #602
