### ISSUE TITLE
CS2 de_anubis export, possible glTF issue, fails loading in some viewers

### ISSUE THREAD

**Issue by pjoe** [ValveResourceFormat/ValveResourceFormat#624]
### Describe the bug

When exporting anubis to gltf, resulting file fails loading in some apps/viewers.

Looks to load correctly in: https://sandbox.babylonjs.com/

Fails importing in Blender 3.6.2 with default import settings (logs attached)

Fails in https://gltf-viewer.donmccurdy.com/

### Relevant log output or exception with stacktrace

```shell
Blender:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\__init__.py", line 1597, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\__init__.py", line 1625, in import_gltf2
    if self.unit_import(path, import_settings) == {'FINISHED'}:
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\__init__.py", line 1645, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 34, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 41, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 36, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 30, in create_vnode
    obj = BlenderNode.create_object(gltf, vnode_id)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_object
    obj = BlenderNode.create_mesh_object(gltf, vnode)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 228, in create_mesh_object
    mesh = BlenderMesh.create(gltf, pynode.mesh, pynode.skin)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 24, in create
    return create_mesh(gltf, mesh_idx, skin_idx)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 45, in create_mesh
    do_primitives(gltf, mesh_idx, skin_idx, mesh, tmp_ob)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 138, in do_primitives
    dtype=ComponentType.to_numpy_dtype(gltf.data.accessors[prim.attributes[attr]].component_type),
KeyError: '_TEXCOORD_4'
```

https://gltf-viewer.donmccurdy.com/
```
index-b24ff50e.js:3555 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'bones')
    at i_.applyBoneTransform (index-b24ff50e.js:3555:100459)
    at i_.computeBoundingBox (index-b24ff50e.js:3555:98291)
    at Rn.expandByObject (index-b24ff50e.js:5:42018)
    at Rn.expandByObject (index-b24ff50e.js:5:42520)
    at Rn.setFromObject (index-b24ff50e.js:5:41228)
    at w1.setContent (index-b24ff50e.js:3583:18970)
    at index-b24ff50e.js:3583:18837
    at index-b24ff50e.js:3555:169458
    at index-b24ff50e.js:3555:193042
```
```


### What game does this happen in

CS2

### Reference file in a Source 2 game

`game/csgo/maps/de_anubis.vpk:/maps/de_amnubis/world.vwrld_c`

### Expected behavior

Exported glTF file can be imported in relevant apps, e.g. Blender

### What version of VRF are you using? On what platform?

5.0.2284+1c8392319..., Windows 11

**Comment by xPaw** [comment]
Well as I said, report this to Blender. And the gltf-viewer bug is something entirely different (and I'm doubting it's our bug)

**Comment by pjoe** [comment]
agree, looks like Blender importer issue, will investigate a bit further, then report there and link/close here

**Comment by pjoe** [comment]
Will try to run gltf validator on output (for some reason can't get it to do that in BJS sandbox)

**Comment by pjoe** [comment]
No errors with the validator:
```
> gltf_validator .\world.gltf
C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\export\maps\anubis\world.gltf
Errors: 0, Warnings: 1, Infos: 11700, Hints: 0
Time: 89960ms
```

**Comment by pjoe** [comment]
Issue in blender importer: https://github.com/KhronosGroup/glTF-Blender-IO/issues/2000
