### ISSUE TITLE
Decompiling CS2 vmap_c files is largely broken

### ISSUE THREAD

**Issue by Nukedrabbit95** [ValveResourceFormat/ValveResourceFormat#629]
### Describe the bug

Opening and decompiling CS2 most release version vmap_c files fails with an error dialog. HLA maps work fine, I never had access to the CS2 beta so I can't be sure if those work.

### Relevant log output or exception with stacktrace

```shell
System.NotImplementedException: Unsupported kv3 entity data type: NULL
   at ValveResourceFormat.ResourceTypes.EntityLump.ConvertKV3TypeToEntityFieldType(KVType type) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 339
   at ValveResourceFormat.ResourceTypes.EntityLump.<ParseEntityPropertiesKV3>g__ReadValues|5_0(KVValue values, <>c__DisplayClass5_0&) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 145
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityPropertiesKV3(IKeyValueCollection entityKv) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 158
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityProperties(IKeyValueCollection entityKv) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 87
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at GUI.Types.Renderer.WorldLoader.LoadEntitiesFromLump(Scene scene, LoadResult result, EntityLump entityLump, String layerName) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 221
   at GUI.Types.Renderer.WorldLoader.Load(Scene scene) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 71
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLWorldViewer.cs:line 154
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLSceneViewer.cs:line 142
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 316
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

Most CS2 vmap_c files. This specific instance was de_overpass

### Expected behavior

I expected it to not give me an error lol

### What version of VRF are you using? On what platform?

5.0.2120

**Comment by Lifeismana** [comment]
use unstable build https://valveresourceformat.github.io/

**Comment by Nukedrabbit95** [comment]
> use unstable build https://valveresourceformat.github.io/
> 
> (Also searching for that error in the issues would have lead you to an issue where that error was resolved)

Apologies, I thought I was on the unstable build (I am very bad at finding things on github)
