### ISSUE TITLE
Decompile error

### ISSUE THREAD

**Issue by ByDexterTR** [ValveResourceFormat/ValveResourceFormat#635]
### Describe the bug

I cannot "Decompile & export" the map de_nuke.vpk

[03:42:00.199] VRF v5.0.2120+5859d5e3f2c412fa89f96fa9bf1ae2585e65a4ee
[03:42:05.818] Opening C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps\de_nuke.vpk
[03:42:09.088] Failed to extract 'de_nuke.vmap_c': System.NotImplementedException: Unsupported kv3 entity data type: NULL
   at ValveResourceFormat.ResourceTypes.EntityLump.ConvertKV3TypeToEntityFieldType(KVType type) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 339
   at ValveResourceFormat.ResourceTypes.EntityLump.<ParseEntityPropertiesKV3>g__ReadValues|5_0(KVValue values, <>c__DisplayClass5_0&) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 145
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityPropertiesKV3(IKeyValueCollection entityKv) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 158
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityProperties(IKeyValueCollection entityKv) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 87
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at ValveResourceFormat.IO.MapExtract.GatherEntitiesFromLump(EntityLump entityLump) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 551
   at ValveResourceFormat.IO.MapExtract.ToValveMap() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 360
   at ValveResourceFormat.IO.MapExtract.ToContentFile() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 229
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 131
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 267
[03:43:25.251] Failed to extract 'de_nuke.vmap_c': System.NotImplementedException: Unsupported kv3 entity data type: NULL
   at ValveResourceFormat.ResourceTypes.EntityLump.ConvertKV3TypeToEntityFieldType(KVType type) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 339
   at ValveResourceFormat.ResourceTypes.EntityLump.<ParseEntityPropertiesKV3>g__ReadValues|5_0(KVValue values, <>c__DisplayClass5_0&) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 145
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityPropertiesKV3(IKeyValueCollection entityKv) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 158
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityProperties(IKeyValueCollection entityKv) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\EntityLump.cs:line 87
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at ValveResourceFormat.IO.MapExtract.GatherEntitiesFromLump(EntityLump entityLump) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 551
   at ValveResourceFormat.IO.MapExtract.ToValveMap() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 360
   at ValveResourceFormat.IO.MapExtract.ToContentFile() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 229
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 131
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 267
[03:43:25.156] Extracting de_nuke.vmap_c to "de_nuke.vmap"
[03:43:25.251] Failed to extract 'de_nuke.vmap_c': Unsupported kv3 entity data type: NULL
[03:43:25.253] Export completed in 00:00:00.0981787.

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps\de_nuke.vpk

### Expected behavior

de_nuke.vmap and its files

### What version of VRF are you using? On what platform?

VRF v5.0.2120+5859d5e3f2c412fa89f96fa9bf1ae2585e65a4ee | Windows 10 Pro 22H2

**Comment by Lifeismana** [comment]
use latest unstable build https://valveresourceformat.github.io/
