### ISSUE TITLE
Decompiler.exe fails to decompile vmdl_c files

### ISSUE THREAD

**Issue by JimmyWoodhouse** [ValveResourceFormat/ValveResourceFormat#637]
### Describe the bug

Attempting to decompile a vmdl_c file causes an exception to occur.

It seems that version 0.4.0 decompiled the vmdl_c to a vmdl file correctly.
However, this does not retrieve the 'mesh' or 'phys' dmx files.
I assume this might be what the 5.0 patch note "Added vmdl_c decompilation to modeldoc vmdl" might be referring to.

### Relevant log output or exception with stacktrace

```shell
Decompiler.exe -i "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\RadGen\temp\vrf_decompiled_models\test\materials\cs_italy\signs\store\italy_bikeshop_sign_1.vmdl_c" -o "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\RadGen\temp\vrf_decompiled_models\test\materials\cs_italy\signs\store\italy_bikeshop_sign_1.vmdl" -d


[1/1] C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\RadGen\temp\vrf_decompiled_models\test\materials\cs_italy\signs\store\italy_bikeshop_sign_1.vmdl_c
File: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\RadGen\temp\vrf_decompiled_models\test\materials\cs_italy\signs\store\italy_bikeshop_sign_1.vmdl_c
System.ArgumentNullException: Value cannot be null. (Parameter 'fileLoader')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at ValveResourceFormat.IO.ModelExtract..ctor(Model model, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ModelExtract.cs:line 61
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 135
   at Decompiler.Decompiler.ProcessFile(String path, Stream stream, String originalPath) in D:\a\ValveResourceFormat\ValveResourceFormat\Decompiler\Decompiler.cs:line 433
        Resource Type: Model [Version 1] [Header Version: 12]
        File Size: 29591 bytes


--- Resource External Refs: ---
        Id:               Resource Name:
        A126CB2ED6B96A3E  materials/cs_italy/signs/store/italy_bikeshop_sign_1.vmat
        7EFF100CD88CAE5F  materials/materials/glass/glass_panels_dirty_01.vmat


--- (No Deferred Resource References Found)


--- Resource Blocks: Count 7 ---
        -- Block: MDAT  Size: 831    bytes [Offset:    112]
        -- Block: MBUF  Size: 12800  bytes [Offset:    944]
        -- Block: PHYS  Size: 13221  bytes [Offset:  13744]
        -- Block: CTRL  Size: 287    bytes [Offset:  26976]
        -- Block: RERL  Size: 151    bytes [Offset:  27264]
        -- Block: RED2  Size: 1350   bytes [Offset:  27424]
        -- Block: DATA  Size: 807    bytes [Offset:  28784]
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

...\materials\cs_italy\signs\store\italy_bikeshop_sign_1.vmdl_c

### Expected behavior

Correctly decompiles the vmdl_c file to export the vmdl file, along with the 'mesh' & 'phys' folders that both contain a dmx file.

### What version of VRF are you using? On what platform?

5.0

**Comment by xPaw** [comment]
Test latest unstable.

**Comment by JimmyWoodhouse** [comment]
Cheers, attempted this using https://github.com/ValveResourceFormat/ValveResourceFormat/actions/runs/6443378697 but the problem persists.
I have been extracting the files from the vpk initially before attempting to decompile them, as I also need to be able to decompile vmdl_c files that are not from the vpk

**Comment by xPaw** [comment]
Cli never supported that (yet), exporting from vpk with cli or gui should work.

**Comment by JimmyWoodhouse** [comment]
Ah brill, thanks. Do you have an idea of when that might be added?
