### ISSUE TITLE
UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 0 (0x0)

### ISSUE THREAD

**Issue by roge** [ValveResourceFormat/ValveResourceFormat#672]
### Describe the bug

A stack trace is reported when attempting to open `script.vts_c` from [this Workshop map](https://steamcommunity.com/sharedfiles/filedetails/?id=3090081856).

### Relevant log output or exception with stacktrace

```shell
ValveResourceFormat.Utils.UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 0 (0x0)
   at ValveResourceFormat.ResourceTypes.BinaryKV3.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\BinaryKV3.cs:line 76
   at ValveResourceFormat.Blocks.ResourceEditInfo2.Read(BinaryReader reader, Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Blocks\ResourceEditInfo2.cs:line 32
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\Resource.cs:line 266
   at GUI.Types.Viewers.Resource.Create(VrfGuiContext vrfGuiContext, Byte[] input) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Viewers\Resource.cs:line 44
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 630
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

The exact `script.vts_c` used when this error was encountered can be downloaded here: https://gist.github.com/roge/dd42705cb8f52cb1fed269a1844d0214/raw/b4411e3cdcae0da5be0be6b0d5d44292f6627a19/script.vts_c

### Expected behavior

The file should open correctly, revealing the script code.

### What version of VRF are you using? On what platform?

v6.0.2421+3742a2813906e7c2b3f569754bc7f66cc85c1726, Windows 10 21H2 19044.3693

**Comment by roge** [comment]
The same issue occurs on v7.0.2479+8b3ade7d8efd5ca8113dd6484b15d39179389b98 as well.

However, the newer version doesn't immediately show the stacktrace. Initially, the tab is blank. If you switch tabs, then the stacktrace is revealed.

Also, this gets printed to the console:
```
[Console] Failed to load "surfaceproperties/surfaceproperties.vsurf_c"
```

**Comment by xPaw** [comment]
However they created the file, it's pretty much corrupted, it has RED2 block but it's empty. Don't do this :)

**Comment by kristiker** [comment]
Seemingly it is made with this https://github.com/Ansimist/cs2typescript
