### ISSUE TITLE
CRC32 mismatch for read data, throws Exception

### ISSUE THREAD

**Issue by Flo4604** [ValveResourceFormat/ValveResourceFormat#696]
### Describe the bug

Dumping the panorama/images/econ/stickers/antwerp2022 images will crash the Decompiler.

The following command can be used to recreate: 

Decompiler --input data/pak01_dir.vpk --vpk_filepath panorama/images/econ/stickers/antwerp2022/ --vpk_extensions vtex_c -o data -d

Edit: found the file which throws

Decompiler --input data/pak01_dir.vpk --vpk_filepath panorama/images/econ/stickers/antwerp2022/sig_hampus_png --vpk_extensions vtex_c -o data -d

--vpk_verify shows VPK verification succeeded, and those files should be the are the latest ones from the 2347770 depot.

The sha1 matches the one from steamdb

94d88af6027e6d94aef7df39b7a4e4899f7af36c  data/pak01_004.vpk

### Relevant log output or exception with stacktrace

```shell
--- Dumping decompiled files...
        [archive index: 004] panorama/images/econ/stickers/antwerp2022/sig_hampus_png.vtex_c
Unhandled exception. System.IO.InvalidDataException: CRC32 mismatch for read data.
   at SteamDatabase.ValvePak.Package.ReadEntry(PackageEntry entry, Byte[]& output, Boolean validateCrc) in /home/runner/work/ValvePak/ValvePak/ValvePak/ValvePak/Package.Read.cs:line 139
   at Decompiler.Decompiler.DumpVPK(String parentPath, Package package, String type, Dictionary`2 manifestData) in /Users/runner/work/ValveResourceFormat/ValveResourceFormat/Decompiler/Decompiler.cs:line 882
   at Decompiler.Decompiler.ParseVPK(String path, Stream stream) in /Users/runner/work/ValveResourceFormat/ValveResourceFormat/Decompiler/Decompiler.cs:line 796
   at Decompiler.Decompiler.ProcessFile(String path, Stream stream, String originalPath) in /Users/runner/work/ValveResourceFormat/ValveResourceFormat/Decompiler/Decompiler.cs:line 402
   at Decompiler.Decompiler.ProcessFile(String path) in /Users/runner/work/ValveResourceFormat/ValveResourceFormat/Decompiler/Decompiler.cs:line 347
   at Decompiler.Decompiler.OnExecute() in /Users/runner/work/ValveResourceFormat/ValveResourceFormat/Decompiler/Decompiler.cs:line 299
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at Decompiler.Decompiler.Main(String[] args) in /Users/runner/work/ValveResourceFormat/ValveResourceFormat/Decompiler/Decompiler.cs:line 131
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

pak01_dir and pak01_004.vpk

### Expected behavior

To show an error which file has a crc32 mismatch and then to skip it, instead of throwing.

### What version of VRF are you using? On what platform?

Version: 7.0.2479+8b3ade7d8efd5ca8113dd6484b15d39179389b98
Runtime: .NET 8.0.0
OS: Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030

**Comment by xPaw** [comment]
There was another person in Discord saying the same thing and their pak_004 was in fact corrupted.

Last unstable build checks hashes of all archives with vpk_verify.
