### ISSUE TITLE
Decompiling s&box default shaders fails

### ISSUE THREAD

**Issue by OEMunlag** [ValveResourceFormat/ValveResourceFormat#699]
### Describe the bug

Using the latest Windows Source2Viewer build, decompiling s&box default shaders (simple, complex, sky, glass, etc), will fail with 'Object reference not set to an instance of an object.'

### Relevant log output or exception with stacktrace

```shell
[21:57:47.849] [ExtractProgressForm] Failed to extract 'simple.shader_c': System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.ShaderExtract..ctor(Resource resource) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ShaderExtract.cs:line 88
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 175
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 368
```

### What game does this happen in

S&box

### Reference file in a Source 2 game

(steam path)\sbox\common\addons\base\shaders\simple.shader_c

### Expected behavior

I'd expect this to output the decompiled (.shader) file from the (.shader_c) file to the specified directory

### What version of VRF are you using? On what platform?

Source 2 Viewer v7.0.2766+b14cdfbc9f316ff8085d2f1c226a50d1c6f6f6e6 (Windows 10)

**Comment by xPaw** [comment]
Can't repro.

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/613331/c54e11a3-82c6-4e27-9c90-5af5ba3018a0)
