### ISSUE TITLE
Compatibility in hla maps compromised (maybe)

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#714]
### Describe the bug

1. Open a3_c17_processing_plant.vpk
2. Open a3_c17_processing_plant.vmap_c
3. See how the it crashes.

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/1bf4ae2f-6e9f-4a6a-9b3c-d60b8c460afe

### Relevant log output or exception with stacktrace

```shell
[00:55:13.495] [Program] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GUI.Types.Renderer.GPUMeshBufferCache.GetVertexArrayObject(Int32 key, VertexDrawBuffer curVertexBuffer, RenderMaterial material, UInt32 idxIndex) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GPUMeshBufferCache.cs:line 58
   at GUI.Types.Renderer.RenderableMesh.CreateDrawCall(IKeyValueCollection objectDrawCall, RenderMaterial material, VBIB vbib) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 339
   at GUI.Types.Renderer.RenderableMesh.ConfigureDrawCalls(Scene scene, VBIB vbib, IKeyValueCollection[] sceneObjects, Dictionary`2 materialReplacementTable) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 213
   at GUI.Types.Renderer.RenderableMesh..ctor(Mesh mesh, Int32 meshIndex, Scene scene, Model model, Dictionary`2 initialMaterialTable, Morph morph, String debugLabel) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\RenderableMesh.cs:line 62
   at GUI.Types.Renderer.ModelSceneNode.LoadMeshes(Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 228
   at GUI.Types.Renderer.ModelSceneNode..ctor(Scene scene, Model model, String skin, Boolean optimizeForMapLoad) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\ModelSceneNode.cs:line 80
   at GUI.Types.Renderer.WorldNodeLoader.Load(Scene scene) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldNodeLoader.cs:line 63
   at GUI.Types.Renderer.WorldLoader.Load() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 79
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 39
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLWorldViewer.cs:line 146
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLSceneViewer.cs:line 223
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 502
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### What game does this happen in

Half life alyx

### Reference file in a Source 2 game

a3_c17_processing_plant.vpk

### Expected behavior

Open the map

### What version of VRF are you using? On what platform?

v8.0.2968 (Windows 10 Pro)

**Comment by xPaw** [comment]
I can't repro this.

**Comment by Unusuario2** [comment]
Is it possible that for version v 8.0 the program has updated its libraries or something like that?

**Comment by xPaw** [comment]
I'm gonna close this, if you can repro this on the latest unstable release, provide a new stacktrace.
