### ISSUE TITLE
System.NotFiniteNumberException when exporting a model from Dota 2 custom game

### ISSUE THREAD

**Issue by UGamer** [ValveResourceFormat/ValveResourceFormat#719]
### Describe the bug

When trying to decompile & export a custom courier model from the workshop custom game "Auto Gladiators" as a glTF or glb file, the following exception occurs.

May be worth noting it can be decompiled/exported as .vmdl and .dmx's, but using Blender addons that open those file types also throws an exception.

### Relevant log output or exception with stacktrace

```shell
[18:41:48.936] [ExtractProgressForm] System.AggregateException: One or more errors occurred. (value)
 ---> System.NotFiniteNumberException: value
   at SharpGLTF.Memory.QuaternionArray.set_Item(Int32 index, Quaternion value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Schema2.AnimationSampler._CreateOutputAccessor(IReadOnlyList`1 output)
   at SharpGLTF.Schema2.AnimationSampler.SetKeys(IReadOnlyDictionary`2 keyframes)
   at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, IDictionary`2 loadedMeshDictionary, String skinName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 496
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, Model model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 342
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 120
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 343
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 98
   --- End of inner exception stack trace ---
```

### What game does this happen in

Dota 2, Auto Gladiators

### Reference file in a Source 2 game

The workshop addon is https://steamcommunity.com/sharedfiles/filedetails/?id=3147450491
models/eom/courier/jinitaimei_1/jinitaimei_1.vmdl_c

### Expected behavior

Model and animations should export as glTF files

### What version of VRF are you using? On what platform?

8.0.3003

**Comment by UGamer** [comment]
Not sure how relevant it is but there's other assets that CAN be decompiled and exported correctly, such as 
models/eom/hero/juggernaut_1/juggernaut_1.vmdl_c

**Comment by xPaw** [comment]
This seems like a broken model, because last bone has NaN bounding box when looking at the ANIM data, and when decoding the frames, angle for the last bone turns Z into NaN.

**Comment by UGamer** [comment]
Gotcha, it seemed that way since it was the only model from the game mode I couldn't decompile.

Thank you for your time :)
