### ISSUE TITLE
very old maps found in the SteamVrPerformanceTest (beta) do not work properly 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#733]
### Describe the bug

the maps of the beta cant be decompiled of render (some of them cant be render but all of the maps can not be decompiled).
Add if possible the option to decompile those maps 
the beta can be found here-  https://valvearchive.com/archive/VR/SteamVR%20PerfTest/Game%20Files/

Decompile
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/f74e65f9-582b-4761-80dd-9e3055fe9c57)

### Relevant log output or exception with stacktrace

```shell
Render
System.IO.InvalidDataException: CRC32 mismatch for read data (expected 5DFBFBD2, got 1C95C907).
   at SteamDatabase.ValvePak.Package.ReadEntry(PackageEntry entry, Byte[] output, Boolean validateCrc) in /home/runner/work/ValvePak/ValvePak/ValvePak/ValvePak/Package.Read.cs:line 165
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry file) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\MainForm.cs:line 629
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

### What game does this happen in

Steamvrperformancetest

### Reference file in a Source 2 game

[vr_aperture_main.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14324626/vr_aperture_main.zip)

### Expected behavior

it does not render or decompile

### What version of VRF are you using? On what platform?

v8.0

**Comment by xPaw** [comment]
Both the screenshot and the log show corrupted files.

**Comment by Unusuario2** [comment]
sorry about that, but is it possible to add decompilation to old source 2 maps? For exaple this (map from teh beta) -
[testdemo_room_2.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14324669/testdemo_room_2.zip)

the error 

[23:24:47.878] [ExtractProgressForm] Failed to extract 'testdemo_room_2.vmap_c': System.InvalidCastException: Specified cast is not valid.
   at ValveResourceFormat.Serialization.IKeyValueCollectionExtensions.GetEnumValue[TEnum](IKeyValueCollection collection, String name, Boolean normalize) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Serialization\IKeyValueCollection.cs:line 108
   at ValveResourceFormat.IO.MapExtract.<AddWorldNodesAsStaticProps>g__SceneObjectToStaticProp|72_5(IKeyValueCollection sceneObject, Int32 layerIndex, List`1 layerNodes) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 457
   at ValveResourceFormat.IO.MapExtract.AddWorldNodesAsStaticProps(WorldNode node) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 667
   at ValveResourceFormat.IO.MapExtract.ToValveMap() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 341
   at ValveResourceFormat.IO.MapExtract.ToContentFile() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MapExtract.cs:line 224
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 130
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 366

**Comment by xPaw** [comment]
I added a few fixes, however these maps are so old we're not going to go out of our way to support them specifically.
