### ISSUE TITLE
Invalid Operation Exception when trying to export Workshop Map as GLTF/GLB.

### ISSUE THREAD

**Issue by SimonNordon4** [ValveResourceFormat/ValveResourceFormat#739]
### Describe the bug

When trying to export community work shop map "surf_boreas.vmap_c" this error occurs. It does not occur when exporting Community map surf_beginner.vmap_c.  It does export to a vmap correctly.

### Relevant log output or exception with stacktrace

```shell
[20:47:25.569] Extracting surf_boreas.vmap_c to "surf_boreas.glb"
[20:47:25.591] System.AggregateException: One or more errors occurred. (Sequence contains no matching element)
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 131
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 343
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 98
   --- End of inner exception stack trace ---
```

### What game does this happen in

Counter Strike 2

### Reference file in a Source 2 game

"SteamLibrary\steamapps\workshop\content\730\3133346713\3133346713.vpk"

### Expected behavior

Expected behaviour is to have the map exported as GLB.

### What version of VRF are you using? On what platform?

v8.1.3204 on Windows 11 64bit

**Comment by kristiker** [comment]
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/203232ef-329e-4db8-8cf1-c0043ff9207c)
