### ISSUE TITLE
sbox maps cannot be viewed in source 2 viewer 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#740]
### Describe the bug

When you try to open a map in source 2 viewer say is this

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/57f48c56-1992-413f-b65c-dd356801b123

### Relevant log output or exception with stacktrace

```shell
[16:06:25.790] [Program] System.Collections.Generic.KeyNotFoundException: The given key 'm_Vertices' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ValveResourceFormat.Serialization.IKeyValueCollectionExtensions.IsNotBlobType(IKeyValueCollection collection, String key) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Serialization\IKeyValueCollection.cs:line 163
   at ValveResourceFormat.ResourceTypes.RubikonPhysics.Shapes.Hull.ParseVertices(IKeyValueCollection data) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\RubikonPhysics\Shapes\Hull.cs:line 189
   at GUI.Types.Renderer.PhysSceneNode.CreatePhysSceneNodes(Scene scene, PhysAggregateData phys, String fileName) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\PhysSceneNode.cs:line 191
   at GUI.Types.Renderer.WorldLoader.LoadWorldPhysics(Scene scene) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 124
   at GUI.Types.Renderer.WorldLoader.Load() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 88
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\WorldLoader.cs:line 39
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLWorldViewer.cs:line 146
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLSceneViewer.cs:line 223
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Controls\GLViewerControl.cs:line 510
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### What game does this happen in

sbox

### Reference file in a Source 2 game

any map in sbox

here is an example i made
[untitled_2.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14396787/untitled_2.zip)

### Expected behavior

it shound not open the map 

### What version of VRF are you using? On what platform?

v8.1.0-unstable

**Comment by Unusuario2** [comment]
I have no idea of what happend but the latest version of VRF can view s&box maps, I am closing this because now works

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/48f59311-690d-496b-98be-15ec094319af

**Comment by kristiker** [comment]
Maybe the map you tested is an earlier compile?
