### ISSUE TITLE
CS2 maps when they are decompile their models (.dmx files) cannot be compiled.

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#753]
### Describe the bug

When you decompile a map and then load the decompile map into hammer the models cant be compiled
[test_decompile.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14792932/test_decompile.zip)

https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/5d63131d-29a7-41bd-a843-8212ecd5d52e

### Relevant log output or exception with stacktrace

```shell
none.
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

test_decompile.vpk

### Expected behavior

Hammer cannot compile the models

### What version of VRF are you using? On what platform?

v8.1.3268

**Comment by kristiker** [comment]
Post error log please. Failed to extract subfile ??? what does it say

**Comment by Unusuario2** [comment]
[18:18:13.777] [ExtractProgressForm] Failed to extract subfile 'maps/test_decompile/worldnodes/node000_world_lr0_agg0_5_reflectivity_30_meshset_0.dmx': System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.ModelExtract.FillDatamodelVertexData(OnDiskBufferData vertexBuffer, DmeVertexData vertexData, VsInputSignature materialInputSignature) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ModelExtract.Mesh.cs:line 259
   at ValveResourceFormat.IO.ModelExtract.ToDmxMesh(Mesh mesh, String name, Dictionary`2 materialInputSignatures, Boolean splitDrawCallsIntoSeparateSubmeshes) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ModelExtract.Mesh.cs:line 377
   at GUI.Forms.ExtractProgressForm.ExtractSubfiles(String contentRelativeFolder, ContentFile contentFile) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 438

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/a34eb3a3-6c9b-49d5-a948-a23cbfc785cb)
