### ISSUE TITLE
Varying parameter 'g_tTintMask' in 'csgo_vertexlitgeneric' could not be resolved

### ISSUE THREAD

**Issue by adenexvfx** [ValveResourceFormat/ValveResourceFormat#755]
### Describe the bug

While bunch decompiling all vmat_c files printing an error and skipping some vmat_c files

### Relevant log output or exception with stacktrace

```shell
File: materials\models\props\de_dust\hr_dust\dust_crates\dust_shipping_crate_01_painted_decals.vmat_c (parent: I:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01_dir.vpk)
System.IO.InvalidDataException: Varying parameter 'g_tTintMask' in 'csgo_vertexlitgeneric' could not be resolved. Features (F_DECAL_BLEND_MODE=1, F_DECAL_TEXTURE=1, F_FORCE_UV2=1, F_TINT_MASK=1)
   at ValveResourceFormat.IO.ShaderDataProvider.<GetInputsForTexture_Internal>g__DetermineParameterReferencedByMaterial|7_2(ShaderCollection shader, Material material, String paramName, KeyValuePair`2 forcedStatic) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ShaderDataProvider.cs:line 212
   at ValveResourceFormat.IO.ShaderDataProvider.<GetInputsForTexture_Internal>g__DetermineParameterReferencedByMaterial|7_2(ShaderCollection shader, Material material, String paramName, KeyValuePair`2 forcedStatic) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ShaderDataProvider.cs:line 207
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture_Internal(String textureType, Material material) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ShaderDataProvider.cs:line 140
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture(String textureType, Material material) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\ShaderDataProvider.cs:line 31
   at ValveResourceFormat.IO.MaterialExtract.GetTextureUnpackInfos(String textureType, String texturePath, Boolean omitDefaults, Boolean omitUniforms)+MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MaterialExtract.cs:line 138
   at ValveResourceFormat.IO.MaterialExtract.ToValveMaterial() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MaterialExtract.cs:line 200
   at ValveResourceFormat.IO.MaterialExtract.ToContentFile() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MaterialExtract.cs:line 49
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 171
   at Decompiler.Decompiler.DumpVPK(String parentPath, Package package, String type, Dictionary`2 manifestData) in D:\a\ValveResourceFormat\ValveResourceFormat\Decompiler\Decompiler.cs:line 988
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

materials\models\props\de_dust\hr_dust\dust_crates\dust_shipping_crate_01_painted_decals.vmat_c
materials\models\props\de_dust\hr_dust\dust_crates\dust_shipping_crate_02_painted_decals.vmat_c

### Expected behavior

Decompile without errors

### What version of VRF are you using? On what platform?

v9.0 Decompiler-windows-x64.zip, Windows platform

**Comment by kristiker** [comment]
What is happening is the features in the material lead to an in-existent shader combo. This can happen when the material is compiled with an earlier shader version that had this combo allowed. The F_eature flags in the material need to be removed based on FeatureRules / Static Combo rules.

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/eb0a9aa0-e325-4f5b-9063-3204d569adb9)
