### ISSUE TITLE
Corrupted textures when exporting maps

### ISSUE THREAD

**Issue by bigstevo** [ValveResourceFormat/ValveResourceFormat#759]
### Describe the bug

Error when decompiling and exporting .vwrld_c to .glTF file.

Here is my workflow:
 - Build map in Hammer and copy the map saved as a .VPK file
	- Path (Assuming CS2 hammer ): C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo_addons\<projectname>\maps\
- Open .VPK in Source 2 Viewer
- Locate the .vwrld_c file. It is common saved under: Maps > world.vwrld_c
- Right click it and select 'decompile and export'. This will then open file explorer
	- Create a folder to contain all the files and select it. 
	- Save as ".glTF"
	- Click 'save'. This will begin de-compiling every texture and exporting them as PNGs, and export the whole map as a GLTF.
- Program then errors out during process of exporting textures with the error below.

### Relevant log output or exception with stacktrace

```shell
[16:32:46.811] [741/959] Exporting texture: metal_plate01_ref_rough_tga_6d31d500.vtex
[16:32:46.812] System.AggregateException: One or more errors occurred. (One or more errors occurred. (Thread is running or terminated; it cannot restart.) (Thread is running or terminated; it cannot restart.) (Thread is running or terminated; it cannot restart.) (Thread is running or terminated; it cannot restart.))
 ---> System.AggregateException: One or more errors occurred. (Thread is running or terminated; it cannot restart.) (Thread is running or terminated; it cannot restart.) (Thread is running or terminated; it cannot restart.) (Thread is running or terminated; it cannot restart.)
 ---> System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartCore()
   at GUI.Types.Renderer.GLTextureDecoder.Decode(SKBitmap bitmap, Resource resource, UInt32 depth, CubemapFace face, UInt32 mipLevel, TextureCodec decodeFlags) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLTextureDecoder.cs:line 76
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap(UInt32 depth, CubemapFace face, UInt32 mipLevel) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 435
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<GenerateGLTFMaterialFromRenderMaterial>g__GetBitmap|2(String texturePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1324
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1262
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 641
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 201
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 126
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 343
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Exporter\ExportFile.cs:line 98
 ---> (Inner Exception #1) System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartCore()
   at GUI.Types.Renderer.GLTextureDecoder.Decode(SKBitmap bitmap, Resource resource, UInt32 depth, CubemapFace face, UInt32 mipLevel, TextureCodec decodeFlags) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLTextureDecoder.cs:line 76
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap(UInt32 depth, CubemapFace face, UInt32 mipLevel) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 435
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<GenerateGLTFMaterialFromRenderMaterial>g__GetBitmap|2(String texturePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1324
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1262<---

 ---> (Inner Exception #2) System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartCore()
   at GUI.Types.Renderer.GLTextureDecoder.Decode(SKBitmap bitmap, Resource resource, UInt32 depth, CubemapFace face, UInt32 mipLevel, TextureCodec decodeFlags) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLTextureDecoder.cs:line 76
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap(UInt32 depth, CubemapFace face, UInt32 mipLevel) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 435
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<GenerateGLTFMaterialFromRenderMaterial>g__GetBitmap|2(String texturePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1324
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1262<---

 ---> (Inner Exception #3) System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartCore()
   at GUI.Types.Renderer.GLTextureDecoder.Decode(SKBitmap bitmap, Resource resource, UInt32 depth, CubemapFace face, UInt32 mipLevel, TextureCodec decodeFlags) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Types\Renderer\GLTextureDecoder.cs:line 76
   at ValveResourceFormat.ResourceTypes.Texture.GenerateBitmap(UInt32 depth, CubemapFace face, UInt32 mipLevel) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\Resource\ResourceTypes\Texture.cs:line 435
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<GenerateGLTFMaterialFromRenderMaterial>g__GetBitmap|2(String texturePath) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1324
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GltfModelExporter.cs:line 1262<---

   --- End of inner exception stack trace ---
[16:32:46.817] [742/961] Exporting texture: constructionlight_rough_tga_5b54b3ec.vtex
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo_addons\test\maps\map.vpk\maps\world.vwrld_c

### Expected behavior

Expecting the map to be decompiled into glTF

### What version of VRF are you using?

9.0.3293+1effaf

**Comment by kristiker** [comment]
Hi, issue with `Thread is running or terminated; it cannot restart.` has been fixed, you can try the latest dev build.

**Comment by bigstevo** [comment]
hey @kristiker thanks for taking the time. Using the newest dev build does a successful export but it seems like the textures get corrupted. I updated my drivers and bios just thinking I might be out of date but did not see a change.

If I attempt to open the vmap_c for viewing or vwrld_c file on the latest stable or dev version I get this error, perhaps it will help:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at GUI.Types.Renderer.SceneAggregate.CreateFragments(KVObject aggregateSceneObject)+MoveNext() in /_/GUI/Types/Renderer/SceneAggregate.cs:line 104
   at GUI.Types.Renderer.WorldNodeLoader.Load(Scene scene) in /_/GUI/Types/Renderer/WorldNodeLoader.cs:line 123
   at GUI.Types.Renderer.WorldLoader.Load() in /_/GUI/Types/Renderer/WorldLoader.cs:line 80
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in /_/GUI/Types/Renderer/WorldLoader.cs:line 40
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in /_/GUI/Types/Renderer/GLWorldViewer.cs:line 162
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in /_/GUI/Types/Renderer/GLSceneViewer.cs:line 262
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in /_/GUI/Controls/GLViewerControl.cs:line 434

Let me know if theres more I can provide here.

**Comment by kristiker** [comment]
Any example of the corruption? If the orm textures look orange-ish that is expected.

**Comment by bigstevo** [comment]
Sure thing. I'll upload an example of a corrupted texture and the VPK here

**Comment by bigstevo** [comment]
![background_foliage_tree_01_ao_tga_30929cac_orm_1516025479](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/46796395/018e8e1f-8a43-4164-bbb8-adf8065daaf6)

Apologies the VPK is too large for github. Heres a google drive link: https://drive.google.com/file/d/10CRt4pgbouNThSCo_a4hVHg1pyfjU0PE/view?usp=sharing

**Comment by xPaw** [comment]
The viewer crash is due to cs_a_sign overlays being aggregate.

Which texture is being corrupted?

**Comment by bigstevo** [comment]
Heya @xPaw . About a quarter of the textures used in the map came out corrupted. All of which were packed in with CS2 and were not custom. If you want I can skim through and provide a list, it's maybe around 70 or so textures, lol. I dont see any commonality between them. It can be the normal, color, ORM, doesn't mater. Here's an example of each which came out corrupted: tarp_01_normal_tga_f478e8ec.png, vertigo_metal_fence_color_psd_7a20b19a.png, safety_glass_1_rough_psd_b8e85b09_orm_1246434028.png

**Comment by xPaw** [comment]
Test last dev build, I just tried it and it exports fine for me.

**Comment by xPaw** [comment]
@bigstevo can you confirm?

**Comment by bigstevo** [comment]
hey @xPaw whoops sorry to get back to you late here. Let me try as of today again with the latest build

**Comment by bigstevo** [comment]
@xPaw I still get corruption on textures after an export from 9.1.3445+a920b94. I can view the .vwrld_c in the viewer perfectly. I'm wondering if I'm like a hardware edge case, lol. Heres my hardware

        Operating System: Windows 11 Home 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
                 Language: English (Regional Setting: English)
      System Manufacturer: ASUS
             System Model: System Product Name
                     BIOS: 1646 (type: UEFI)
                Processor: 13th Gen Intel(R) Core(TM) i7-13700F (24 CPUs), ~2.1GHz
                   Memory: 32768MB RAM
           Card name: NVIDIA GeForce GTX 1660 Ti

**Comment by kristiker** [comment]
Do vtex_c files opened in viewer display fine? With and without software decode.

**Comment by xPaw** [comment]
Since you're ssaying viewer works fine, try saving or copying to clipboard from the texture viewer (as that does a pixels read)

Also what driver version?

**Comment by bigstevo** [comment]
> Do vtex_c files opened in viewer display fine? With and without software decode.

@kristiker 

Yes, they view fine with both settings.

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/46796395/98d8eb73-51ae-41a5-9ebd-f4d505e36dfa)

**Comment by bigstevo** [comment]
> Since you're saying viewer works fine, try saving or copying to clipboard from the texture viewer (as that does a pixels read)
> 
> Also try exporting a single vmat_c file.
> 
> Also what driver version?

@xPaw 

Copying / saving from texture viewer does not export corruption:

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/46796395/7e3096ab-d174-4fe1-98d7-3feef4dd1f61)

From comment above this is one texture example that exports corrupted.

Exporting single vmat_c to vmat exports all textures correctly as well

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/46796395/908c314c-53bc-41c5-a4e6-c510a686a96a)

Nvidia driver ver: 546.65

**Comment by xPaw** [comment]
Are the same files corrupted when you export a map, or do they change from every export?

Try exporting different maps. If you're willing, try exporting with the CLI.

**Comment by bigstevo** [comment]
heya @xPaw, random textures have corruption every time.

Is there a wiki page for exporting with CLI? Not sure how to do that.

**Comment by xPaw** [comment]
This sounds like a hardware or driver issue, I don't know how we would repro or fix this.

**Comment by bigstevo** [comment]
Yeah, especially if you folks could export that exact map with no issues. Not sure what else we could do beyond shipping my computer to ya
