### ISSUE TITLE
gltf: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by thecatontheflat** [ValveResourceFormat/ValveResourceFormat#765]
### Describe the bug

A workshop map won't decompile because of the error.
I tried both CLI Decomiler and the GUI.

### Relevant log output or exception with stacktrace

```shell
[19:55:45.959] System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
 ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.TextureExtract.ToPngImageChannels(SKBitmap bitmap, ChannelMapping channel) in /_/ValveResourceFormat/IO/TextureExtract.cs:line 234
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 1262
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ValveResourceFormat.IO.GltfModelExporter.WriteModelFile(ModelRoot exportedModel, String filePath) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 641
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 201
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 126
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 343
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in /_/GUI/Types/Exporter/ExportFile.cs:line 98
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.TextureExtract.ToPngImageChannels(SKBitmap bitmap, ChannelMapping channel) in /_/ValveResourceFormat/IO/TextureExtract.cs:line 234
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 1262<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.TextureExtract.ToPngImageChannels(SKBitmap bitmap, ChannelMapping channel) in /_/ValveResourceFormat/IO/TextureExtract.cs:line 234
   at ValveResourceFormat.IO.GltfModelExporter.<>c__DisplayClass56_0.<<GenerateGLTFMaterialFromRenderMaterial>g__AddTexture|3>d.MoveNext() in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 1352
--- End of stack trace from previous location ---
   at ValveResourceFormat.IO.GltfModelExporter.GenerateGLTFMaterialFromRenderMaterial(Material material, Material renderMaterial, ModelRoot model) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 1262<---

   --- End of inner exception stack trace ---
[19:55:45.962] Found existing material: powder_snow
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

Workshop map can be downloaded from here: https://ufile.io/qis7rntj

Alternatively, by changing the CS2 server to the workshop map de_powder:

host_workshop_map 3082615164

### Expected behavior

The file is decompiled successfully

### What version of VRF are you using?

9.0.3398 42bbc3b15dbdd3f05bc2ce7a16960cb92c5965fa on Microsoft Windows NT 10.0.22631.0

**Comment by xPaw** [comment]
It's crashing when trying to export textures/metal038_4k-jpg/metal038_1k_color_png_69f73623.vtex which is missing from the vpk.

**Comment by thecatontheflat** [comment]
Thanks for clarifying it @xPaw .

Is it possible to export it while ignoring the missing textures? I believe it would still be useful, since game engine is able to cope with that anyhow

**Comment by xPaw** [comment]
It's fixed in dev build, it will export a 1x1 placeholder.

**Comment by thecatontheflat** [comment]
Sorry I missed that commit. I confirm that it works now, thank you so much! ❤️
