### ISSUE TITLE
VRF cannot decompile old vmat_c files properly 

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#767]
### Describe the bug

self explanatory.

The file: 
[toolswhite.zip](https://github.com/ValveResourceFormat/ValveResourceFormat/files/14968529/toolswhite.zip)

### Relevant log output or exception with stacktrace

```shell
Failed to extract 'materials/tools/toolswhite.vmat_c': System.ArgumentOutOfRangeException: Index value mismatch 0x36 at position 0 (0x01C46536). (Parameter 'packedValue')
   at ValveResourceFormat.CompiledShader.ChannelMapping..ctor(UInt32 packedValue) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\CompiledShader\ChannelMapping.cs:line 57
   at ValveResourceFormat.CompiledShader.ChannelBlock..ctor(ShaderDataReader datareader, Int32 blockIndex) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderDataBlocks.cs:line 788
   at ValveResourceFormat.CompiledShader.ShaderFile.ParseFile() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderFile.cs:line 183
   at ValveResourceFormat.CompiledShader.ShaderFile.Read(String filenamepath, Stream input) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\CompiledShader\ShaderFile.cs:line 101
   at ValveResourceFormat.IO.GameFileLoader.<LoadShaderFromDisk>g__TryLoadShader|20_0(VcsProgramType programType, VcsPlatformType platformType, VcsShaderModelType modelType, <>c__DisplayClass20_0&) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GameFileLoader.cs:line 232
   at ValveResourceFormat.IO.GameFileLoader.LoadShaderFromDisk(String shaderName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GameFileLoader.cs:line 257
   at ValveResourceFormat.IO.GameFileLoader.LoadShader(String shaderName) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\GameFileLoader.cs:line 290
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture_Internal(String textureType, Material material)
   at ValveResourceFormat.IO.MaterialExtract.GetTextureUnpackInfos(String textureType, String texturePath, Boolean omitDefaults, Boolean omitUniforms)+MoveNext() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MaterialExtract.cs:line 138
   at ValveResourceFormat.IO.MaterialExtract.ToValveMaterial() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MaterialExtract.cs:line 200
   at ValveResourceFormat.IO.MaterialExtract.ToContentFile() in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\MaterialExtract.cs:line 49
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader) in D:\a\ValveResourceFormat\ValveResourceFormat\ValveResourceFormat\IO\FileExtract.cs:line 171
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in D:\a\ValveResourceFormat\ValveResourceFormat\GUI\Forms\ExtractProgressForm.cs:line 366
```

### What game does this happen in

SteamVrbeta

### Reference file in a Source 2 game

materials/tools/toolswhite.vmat_c

### Expected behavior

it shound not decompile the file

### What version of VRF are you using?

9.0.3293

**Comment by kristiker** [comment]
Can you upload the failing compiled shader (vcs) files that this material uses?
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/26466974/f45aebd1-19c9-406e-b290-1fed742c16e6)
