### ISSUE TITLE
Exception when exporting & decompiling CS2's `core\pak01_dir.vpk`

### ISSUE THREAD

**Issue by szmarczak** [ValveResourceFormat/ValveResourceFormat#773]
### Describe the bug

```
[18:10:33.067] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.FileExtract.GetExtension(Resource resource) in /_/ValveResourceFormat/IO/FileExtract.cs:line 298
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 354
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in /_/GUI/Forms/ExtractProgressForm.cs:line 333
   at GUI.Forms.ExtractProgressForm.<OnShown>b__20_0() in /_/GUI/Forms/ExtractProgressForm.cs:line 213
   --- End of inner exception stack trace ---
```

### Relevant log output or exception with stacktrace

```shell
[18:10:16.354] Folder export started to "C:\pak01"
[18:10:16.359] Extracting Models…
[18:10:16.364] Extracting models/actors/ghost_speaker.vmdl_c
[18:10:16.380] + models/actors/ghost_speaker.vmdl
[18:10:16.479]   + models/actors/idle.dmx
[...]
[18:10:32.833] Extracting sounds/constant_synthesis_container.vsnd_c
[18:10:32.836] + sounds/constant_synthesis_container.wav
[18:10:32.840] Extracting sounds/dynamic_engine_container.vsnd_c
[18:10:33.067] System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ValveResourceFormat.IO.FileExtract.GetExtension(Resource resource) in /_/ValveResourceFormat/IO/FileExtract.cs:line 298
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 354
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in /_/GUI/Forms/ExtractProgressForm.cs:line 333
   at GUI.Forms.ExtractProgressForm.<OnShown>b__20_0() in /_/GUI/Forms/ExtractProgressForm.cs:line 213
   --- End of inner exception stack trace ---
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

core\pak01_dir.vpk

### Expected behavior

No error.

### What version of VRF are you using?

v9.0.3420

**Comment by xPaw** [comment]
dynamic_engine_container.vsnd_c fails to extract because it's an empty sound, so it has no actual sound data.

**Comment by dirtkiller23** [comment]
Source sound container files (rename the extension to .vsnd to compile)

[scaryblend.txt](https://github.com/user-attachments/files/23504330/scaryblend.txt)
[tapeplayer.txt](https://github.com/user-attachments/files/23504331/tapeplayer.txt)
[looping_test.txt](https://github.com/user-attachments/files/23504332/looping_test.txt)

Compiled sound container files (CTRL block from the vsnd_c files)

[scaryblend.txt](https://github.com/user-attachments/files/23504362/scaryblend.txt)
[tapeplayer.txt](https://github.com/user-attachments/files/23504360/tapeplayer.txt)
[looping_test.txt](https://github.com/user-attachments/files/23504361/looping_test.txt)
