### ISSUE TITLE
unrecognized block type "FLCI"

### ISSUE THREAD

**Issue by FreeAgentLS** [ValveResourceFormat/ValveResourceFormat#793]
### Describe the bug

After today's update of CS2
weapon.vdata_c cant be decomplie

### Relevant log output or exception with stacktrace

```shell
- Welcome to Source 2 Viewer v9.2.3481+3af705de937d1f4065354648f5a7b9b547500b92
- If you are experiencing an issue, try using latest dev build from https://valveresourceformat.github.io/

[06:17:43.263] [MainForm] Opening D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01_dir.vpk
[06:17:43.274] [Console] Found "Counter-Strike 2" from "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\gameinfo.gi"
[06:17:43.275] [Console] Added folder "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo" to game search paths
[06:17:43.275] [Console] Preloading vpk "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo_imported\pak01_dir.vpk"
[06:17:43.276] [Console] Added folder "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo_imported" to game search paths
[06:17:43.276] [Console] Preloading vpk "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo_core\pak01_dir.vpk"
[06:17:43.276] [Console] Added folder "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo_core" to game search paths
[06:17:43.276] [Console] Preloading vpk "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\core\pak01_dir.vpk"
[06:17:43.278] [Console] Added folder "D:\Softwares\Steam\steamapps\common\Counter-Strike Global Offensive\game\core" to game search paths
[06:17:47.368] [Program] System.ArgumentException: Unrecognized block type 'FLCI'
   at ValveResourceFormat.Resource.ConstructFromType(String input) in /_/ValveResourceFormat/Resource/Resource.cs:line 405
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 267
   at GUI.Types.Exporter.ExportFile.ExtractFileFromStream(String fileName, Stream stream, VrfGuiContext vrfGuiContext, Boolean decompile) in /_/GUI/Types/Exporter/ExportFile.cs:line 41
   at GUI.MainForm.ExtractFiles(Object sender, Boolean decompile) in /_/GUI/MainForm.ContextMenus.cs:line 268
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
[06:18:07.269] [Program] System.ArgumentException: Unrecognized block type 'FLCI'
   at ValveResourceFormat.Resource.ConstructFromType(String input) in /_/ValveResourceFormat/Resource/Resource.cs:line 405
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 267
   at GUI.Types.Exporter.ExportFile.ExtractFileFromStream(String fileName, Stream stream, VrfGuiContext vrfGuiContext, Boolean decompile) in /_/GUI/Types/Exporter/ExportFile.cs:line 41
   at GUI.MainForm.ExtractFiles(Object sender, Boolean decompile) in /_/GUI/MainForm.ContextMenus.cs:line 295
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

Counter-Strike Global Offensive\game\csgo\pak01_dir.vpk

### Expected behavior

it should be decompiled

### What version of VRF are you using?

9.2.3481 3af705de937d1f4065354648f5a7b9b547500b92 on Microsoft Windows NT 10.0.19045.0

**Comment by xPaw** [comment]
That's fixed in dev.

**Comment by FreeAgentLS** [comment]
> That's fixed in dev.

thanks
