### ISSUE TITLE
VRF cannot open the vmap_c and vwrld_c of my HLA map

### ISSUE THREAD

**Issue by Unusuario2** [ValveResourceFormat/ValveResourceFormat#804]
### Describe the bug

Self explanatory.
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/2b5a84ff-3304-4f3c-bd27-7444a3a3677c)
![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/110506367/8e8589dd-4029-4ef9-bbc2-1295045d7cfe)

Files: [vmap_c&vwrld_c.zip](https://github.com/user-attachments/files/15521153/vmap_c.vwrld_c.zip)

### Expected behavior

It should open it

### Relevant log output or exception with stacktrace

```shell
System.InvalidCastException: Specified cast is not valid.
   at GUI.Types.Renderer.WorldLoader.LoadEntitiesFromLump(EntityLump entityLump, String layerName, Matrix4x4 parentTransform) in /_/GUI/Types/Renderer/WorldLoader.cs:line 779
   at GUI.Types.Renderer.WorldLoader.Load() in /_/GUI/Types/Renderer/WorldLoader.cs:line 76
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in /_/GUI/Types/Renderer/WorldLoader.cs:line 52
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in /_/GUI/Types/Renderer/GLWorldViewer.cs:line 173
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in /_/GUI/Types/Renderer/GLSceneViewer.cs:line 272
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in /_/GUI/Controls/GLViewerControl.cs:line 438
```

### What game does this happen in

Half life Alyx 

### Reference file in a Source 2 game

vmap_c&vwrld_c.zip

### What version of VRF are you using? Test latest dev build.

10.0.3621

**Comment by xPaw** [comment]
There's nothing to be fixed since you are not sharing the full map. You probably screwed some entity.
