### ISSUE TITLE
"System.ArgumentNullException: Value cannot be null. (Parameter 'key')" when decompiling vmap

### ISSUE THREAD

**Issue by techsideofficial** [ValveResourceFormat/ValveResourceFormat#813]
### Describe the bug

These files cannot be decompiled.

### Expected behavior

It should decompile into 'vmap' and 'vwrld'

### Relevant log output or exception with stacktrace

```shell
[13:13:24.901] [Console] System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at ValveResourceFormat.Serialization.KeyValues.KeyValues3.SeekValue(Char c, Parser parser) in /_/ValveResourceFormat/Serialization/KeyValues/KeyValues3.cs:line 250
   at ValveResourceFormat.Serialization.KeyValues.KeyValues3.ParseKVFile(Stream fileStream) in /_/ValveResourceFormat/Serialization/KeyValues/KeyValues3.cs:line 113
   at ValveResourceFormat.IO.ModelExtract.<>c__DisplayClass100_0.<ToValveModel>g__ExtractModelKeyValues|5(KVObject rootNode) in /_/ValveResourceFormat/IO/ModelExtract.ValveModel.cs:line 813
```

### What game does this happen in

SteamVR Home Workshop Items

### Reference file in a Source 2 game

"C:\Program Files (x86)\Steam\steamapps\workshop\content\250820\1594890070\1594890070.vpk"

### What version of VRF are you using?

10.0.3595 b43f88ee14fdf0da91faf781f9bc171492bf15e2 on Microsoft Windows NT 10.0.22631.0 (GPU: Intel(R) Iris(R) Xe Graphics, Driver: 4.6.0 - Build 30.0.101.1960)

**Comment by kristiker** [comment]
I thought we fixed models with null or empty keyvalues string, so that's weird.

**Comment by techsideofficial** [comment]
@kristiker It seems to only happen on some maps. Is it fixable?
