### ISSUE TITLE
"Unsupported array length of 60" when opening deadlock street_test map

### ISSUE THREAD

**Issue by z3nnik** [ValveResourceFormat/ValveResourceFormat#835]
### Describe the bug

When opening or decompiling vmap_c of the street_test.vpk map of the game deadlock I get a NotImplementedException

https://github.com/ValveResourceFormat/ValveResourceFormat/blob/cc0cb839bfd9a4b6f85c4e7aaafc80e4e361b628/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs#L166 

### Expected behavior

correct map opening or workaround

### Relevant log output or exception with stacktrace

```shell
System.NotImplementedException: Unsupported array length of 60
   at ValveResourceFormat.ResourceTypes.EntityLump.ReadValues(Entity entity, KVValue values) in /_/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs:line 160
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityPropertiesKV3(KVObject entityKv) in /_/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs:line 129
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityProperties(KVObject entityKv) in /_/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs:line 103
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at GUI.Types.Renderer.WorldLoader.LoadEntitiesFromLump(EntityLump entityLump, String layerName, Matrix4x4 parentTransform) in /_/GUI/Types/Renderer/WorldLoader.cs:line 260
   at GUI.Types.Renderer.WorldLoader.Load() in /_/GUI/Types/Renderer/WorldLoader.cs:line 76
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in /_/GUI/Types/Renderer/WorldLoader.cs:line 52
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in /_/GUI/Types/Renderer/GLWorldViewer.cs:line 173
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in /_/GUI/Types/Renderer/GLSceneViewer.cs:line 272
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in /_/GUI/Controls/GLViewerControl.cs:line 438
```

### What game does this happen in

Deadlock

### Reference file in a Source 2 game

..SteamLibrary\steamapps\common\Project8Staging\game\citadel\maps\street_test.vpk
- street_test.vmap_c

### What version of VRF are you using?

10.1.3729 6a8d02a98936c7c16ececfc0968b560c8efa4c01 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 560.94)

**Comment by xPaw** [comment]
That was fixed already.
