### ISSUE TITLE
Cannot export de_overpass due to: Accessor[672] memory: Value[37] is out of bounds 15. (Parameter 'memory')

### ISSUE THREAD

**Issue by thecatontheflat** [ValveResourceFormat/ValveResourceFormat#836]
### Describe the bug

Exporting CS2 de_overpass map to GLFT fails.

I use Decompiler CLI with the following args:

```
./decompiler/Decompiler', `-i /csgo/game/csgo/maps/de_overpass.vpk -o /tmp/overpass.glb -f maps/de_overpass/world.vwrld_c --vpk_decompile --gltf_export_materials --threads 12 --gltf_export_format glb --gltf_export_extras
```

### Expected behavior

Exporting CS2 de_overpass map to GLFT should work

### Relevant log output or exception with stacktrace

```shell
File: maps/de_overpass/world.vwrld_c (parent: /csgo/game/csgo/maps/de_overpass.vpk)
SharpGLTF.Validation.DataException: Accessor[672] memory: Value[37] is out of bounds 15. (Parameter 'memory')
   at SharpGLTF.Validation.ValidationContext._DataThrow(ValueLocation pname, String msg)
   at SharpGLTF.Validation.ValidationContext.That(Action action)
   at SharpGLTF.Schema2.Accessor.ValidateIndices(ValidationContext validate, UInt32 vertexCount, PrimitiveType drawingType)
   at SharpGLTF.Schema2.MeshPrimitive.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.Mesh.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.ExtraProperties.OnValidateContent(ValidationContext validate)
   at SharpGLTF.Schema2.WriteContext._ValidateBeforeWriting(ModelRoot model)
   at SharpGLTF.Schema2.WriteContext.WriteBinarySchema2(String name, ModelRoot model)
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 193
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 120
   at Decompiler.Decompiler.DumpVPK(String parentPath, Package package, String type, Dictionary`2 manifestData) in /_/Decompiler/Decompiler.cs:line 1026
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

/csgo/game/csgo/maps/de_overpass.vpk

### What version of VRF are you using?

Version: 10.1.3729+6a8d02a98936c7c16ececfc0968b560c8efa4c01

**Comment by xPaw** [comment]
Uncommenting DEBUG_VALIDATE_GLTF should narrow down which file specifically is caused the bug.

**Comment by thecatontheflat** [comment]
Is there a flag I could use instead that would increase verbosity (using a compiled build)?

**Comment by xPaw** [comment]
Nope.

**Comment by xPaw** [comment]
Does not repro for me.

**Comment by thecatontheflat** [comment]
It works in 10.2! Thank you so much! 🔥🔥🔥
