### ISSUE TITLE
When exporting a vpk 

### ISSUE THREAD

**Issue by quqech** [ValveResourceFormat/ValveResourceFormat#837]
### Describe the bug

I cant export the vpk into any folder doesnt matter if it is drive C:/ or drive D:/

### Expected behavior

Was expected to export files within the vpk to a destination folder

### Relevant log output or exception with stacktrace

```shell
[14:58:19.164] Folder export started to "C:\RAGEMP"
[14:58:19.166] Extracting models/heroes/pudge/back.vmdl_c"
[14:58:19.169] System.AggregateException: One or more errors occurred. (The filename, directory name, or volume label syntax is incorrect. : 'C:\RAGEMP\models\heroes\pudge\back.vmdl_c"')
 ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\RAGEMP\models\heroes\pudge\back.vmdl_c"'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in /_/GUI/Forms/ExtractProgressForm.cs:line 347
   at GUI.Forms.ExtractProgressForm.<OnShown>b__23_0() in /_/GUI/Forms/ExtractProgressForm.cs:line 221
   --- End of inner exception stack trace ---
```

### What game does this happen in

Dota2

### Reference file in a Source 2 game

dota 2 beta\game\dota\pak01_000.vpk

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.19045.0 (GPU: AMD Radeon RX 6700 XT, Driver: 4.6.0 Compatibility Profile Context 24.7.1.240711)

**Comment by xPaw** [comment]
Are you putting a quote `"` into the file name when exporting?

**Comment by quqech** [comment]
> Are you putting a quote `"` into the file name when exporting?

No, but a found a workaround exporting each folder from vpk individialy

**Comment by xPaw** [comment]
Provide full steps on how are you getting this error, maybe a video.

**Comment by xPaw** [comment]
@quqech can you provide details or do we close this?
