### ISSUE TITLE
world_physics.vmdl_c->PHYS not get string correctly

### ISSUE THREAD

**Issue by qingkewx** [ValveResourceFormat/ValveResourceFormat#840]
### Describe the bug

when analyzing the deadline street_test-.pk, it is not possible to obtain a normal string when obtaining the PHYS in world_physics.vmdl_c
![ed77be5f7b89621b73fea25ca17f1ad2](https://github.com/user-attachments/assets/d531811c-9e05-47d5-8510-959f082aa472)
![52dbc6b82a47466f61c207a39cad65f6](https://github.com/user-attachments/assets/cef6e6f8-a34f-4f8b-90a0-b2e54de15c61)

### Expected behavior

perhaps it's due to the large file size? hope to obtain the string correctly

### What game does this happen in

deadlock

### Reference file in a Source 2 game

Steam\steamapps\common\Deadlock\game\citadel\maps\street_test.vpk

### What version of VRF are you using?

v10.2.3850

**Comment by xPaw** [comment]
The problem here is "fast" colored text box. It does actually get stringified just fine, but it can't get displayed because the text viewer allocates so much memory.

You can dump the block with the cli utility.

**Comment by xPaw** [comment]
The issue here is that street_test is such a big map, the string builder for PHYS block has a length of 1.3gb, and for some reason calling StringBuilder.ToString throws OOM due to some limitation of the .NET runtime.

**Comment by maoxian123** [comment]
so how to solve this?

**Comment by qingkewx** [comment]
> so how to solve this?
rewritten ToString and export phys directly

**Comment by maoxian123** [comment]
> > so how to solve this?
> > rewritten ToString and export phys directly

any example code or it will fix in next version?

**Comment by commmmmiiitz** [comment]
faced the same problem with the newly released counter strike maps.

i suggest a check on the length of `block`, then if the size is to big the user could be asked if the content should be written to a file instead...

for a temporary solution the following code just writes it to a file (added in /GUI/Types/Viewers/Resource.cs)

```
string filePath = AppDomain.CurrentDomain.BaseDirectory + $"\\vphys";
var input = resource.FileName;
var fileName = input.Replace("maps/", "").Replace("/world_physics.vmdl_c", "");

if (block.Type == BlockType.PHYS)
{
    File.WriteAllText(filePath + $"\\{fileName}.vphys", block.ToString());
}
```

**Comment by xPaw** [comment]
This solution won't help you much when the phys string reaches 2 gigs. Proper solution would be to add exporting into a binary format (like gltf).

**Comment by commmmmiiitz** [comment]
oh im sorry i think i got the issue kinda mixed up, i can execute the toString just fine... but the output (in the ui) is to big for the clipboard (i assume) so i guess its kinda releated...

When attempting to copy the output i get a OOM.

![Image](https://github.com/user-attachments/assets/3f550543-6f6b-4cb8-bd1d-8e1009a63469)

Console logs it like this:
```
[Program] System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.AppendWithExpansion(Char& value, Int32 valueCount)
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.Text.StringBuilder.AppendFormat(String format, Object arg0, Object arg1)
   at FastColoredTextBoxNS.ExportToHTML.Flush(StringBuilder sb, StringBuilder tempSB, StyleIndex currentStyle)
   at FastColoredTextBoxNS.ExportToHTML.GetHtml(Range r)
   at FastColoredTextBoxNS.FastColoredTextBox.OnCreateClipboardData(DataObject data)
   at FastColoredTextBoxNS.FastColoredTextBox.Copy()
   at FastColoredTextBoxNS.FastColoredTextBox.DoAction(FCTBAction action)
   at FastColoredTextBoxNS.FastColoredTextBox.ProcessKey(Keys keyData)
   at FastColoredTextBoxNS.FastColoredTextBox.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at FastColoredTextBoxNS.FastColoredTextBox.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at FastColoredTextBoxNS.FastColoredTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by xPaw** [comment]
have you tried dumping the `-b PHYS` with the cli? Then you can redirect the output to a file at least.

**Comment by commmmmiiitz** [comment]
yup that works well... thank you 👍 great work on the tools
