### ISSUE TITLE
_vmap_c stopped opening after the game's recent update

### ISSUE THREAD

**Issue by sikleq** [ValveResourceFormat/ValveResourceFormat#849]
### Describe the bug

Returns error "unsupported array length of 1". S2V is up to date.

### Expected behavior

Should be working.

### Relevant log output or exception with stacktrace

- Welcome to Source 2 Viewer v10.2.3850+4f2f81e04a752675cb4c31ee6572d4c53e0bb321
- If you are experiencing an issue, try using latest dev build from https://valveresourceformat.github.io/

[13:51:49.358] [MainForm] Opening C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\citadel\maps\dl_streets.vpk
[13:51:49.392] [Console] Found "citadel" from "C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\citadel\gameinfo.gi"
[13:51:49.392] [Console] Preloading vpk "C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\citadel\pak01_dir.vpk"
[13:51:49.469] [Console] Added folder "C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\citadel" to game search paths
[13:51:49.469] [Console] Preloading vpk "C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\core\pak01_dir.vpk"
[13:51:49.470] [Console] Added folder "C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\core" to game search paths
[13:51:50.545] [OpenGL] GPU: NVIDIA GeForce RTX 3060/PCIe/SSE2, Driver: 4.6.0 NVIDIA 565.90, OS: Microsoft Windows NT 10.0.22631.0
[13:51:50.654] [ShaderLoader] Shader 'vrf.font_msdf' as 'font_msdf' () compiled and linked succesfully
[13:51:50.731] [ShaderLoader] Shader 'vrf.post_process' as 'post_processing' () compiled and linked succesfully
[13:51:50.762] [ShaderLoader] Shader 'vrf.grid' as 'grid' () compiled and linked succesfully
[13:51:50.781] [ShaderLoader] Shader 'vrf.background' as 'background' () compiled and linked succesfully
[13:51:50.787] [ShaderLoader] Shader 'vrf.default' as 'default' () compiled and linked succesfully
[13:51:50.818] [ShaderLoader] Shader 'vrf.picking' as 'picking' () compiled and linked succesfully
[13:51:50.826] [ShaderLoader] Shader 'vrf.depth_only' as 'depth_only' () compiled and linked succesfully
[13:51:50.851] [ShaderLoader] Shader 'vrf.depth_only' as 'depth_only' (D_ANIMATED) compiled and linked succesfully
[13:51:51.696] [Program] System.NotImplementedException: Unsupported array length of 1
   at ValveResourceFormat.ResourceTypes.EntityLump.ReadValues(Entity entity, KVValue values) in /_/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs:line 166
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityPropertiesKV3(KVObject entityKv) in /_/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs:line 129
   at ValveResourceFormat.ResourceTypes.EntityLump.ParseEntityProperties(KVObject entityKv) in /_/ValveResourceFormat/Resource/ResourceTypes/EntityLump.cs:line 103
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at GUI.Types.Renderer.WorldLoader.LoadEntitiesFromLump(EntityLump entityLump, String layerName, Matrix4x4 parentTransform) in /_/GUI/Types/Renderer/WorldLoader.cs:line 260
   at GUI.Types.Renderer.WorldLoader.Load() in /_/GUI/Types/Renderer/WorldLoader.cs:line 76
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in /_/GUI/Types/Renderer/WorldLoader.cs:line 52
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in /_/GUI/Types/Renderer/GLWorldViewer.cs:line 173
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in /_/GUI/Types/Renderer/GLSceneViewer.cs:line 296
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in /_/GUI/Controls/GLViewerControl.cs:line 439
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

### What game does this happen in

Deadlock

### Reference file in a Source 2 game

\Steam\steamapps\common\Deadlock\game\citadel\maps\dl_streets.vpk\dl_streets_vmap_c

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 3060/PCIe/SSE2, Driver: 4.6.0 NVIDIA 565.90)

**Comment by xPaw** [comment]
This was already fixed in unstable build.
