### ISSUE TITLE
vmat_c Error decompling no longer referenced texture after game shader update

### ISSUE THREAD

**Issue by SpsZaPIZZA** [ValveResourceFormat/ValveResourceFormat#857]
### Describe the bug

Failed to extract Features file for 'csgo_environment' does not contain a parameter named 'g_tAmbientOcclusion'

### Expected behavior

Decompile .vmat_c to vmat

### Relevant log output or exception with stacktrace

```shell
18:48:24.508] [ExtractProgressForm] Failed to extract 'gris_1024_shiny.vmat_c': System.IO.InvalidDataException: Features file for 'csgo_environment' does not contain a parameter named 'g_tAmbientOcclusion'
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture_Internal(String textureType, Material material) in /_/ValveResourceFormat/IO/ShaderDataProvider.cs:line 165
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture(String textureType, Material material) in /_/ValveResourceFormat/IO/ShaderDataProvider.cs:line 31
   at ValveResourceFormat.IO.MaterialExtract.GetTextureUnpackInfos(String textureType, String texturePath, Boolean omitDefaults, Boolean omitUniforms)+MoveNext() in /_/ValveResourceFormat/IO/MaterialExtract.cs:line 138
   at ValveResourceFormat.IO.MaterialExtract.ToValveMaterial() in /_/ValveResourceFormat/IO/MaterialExtract.cs:line 200
   at ValveResourceFormat.IO.MaterialExtract.ToContentFile() in /_/ValveResourceFormat/IO/MaterialExtract.cs:line 49
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader, IProgress`1 progress) in /_/ValveResourceFormat/IO/FileExtract.cs:line 174
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 406
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

materials/lego/gris_1024_shiny_color.vmat_c

### What version of VRF are you using?

10.2.3935 b817e1d47010c8ef0a41e359965d9d28a81dce66 on Microsoft Windows NT 10.0.19045.0 (GPU: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 566.03)

**Comment by kristiker** [comment]
Did csgo_environment remove support for amient occlusion in one of the recent updates?

**Comment by SpsZaPIZZA** [comment]
![Image](https://github.com/user-attachments/assets/131e4ea3-2926-4fb3-89c3-99758df4f238)
No

**Comment by SpsZaPIZZA** [comment]
> Did csgo_environment remove support for amient occlusion in one of the recent updates?

![Image](https://github.com/user-attachments/assets/0204d45a-ce36-4267-a392-cc8688e0888e)
No

**Comment by kristiker** [comment]
I think it packs the textures differently then. (This can be seen in compiled textures tab)

**Comment by SpsZaPIZZA** [comment]
> I think it packs the textures differently then. (This can be seen in compiled textures tab)

![Image](https://github.com/user-attachments/assets/b4a72e36-ecc0-4306-a0a0-b7ccf7a18cd9)
