### ISSUE TITLE
Unable to open the latest version of CS2 maps

### ISSUE THREAD

**Issue by JonasAlmaas** [ValveResourceFormat/ValveResourceFormat#861]
### Describe the bug

Error when trying to preview the latest version of Overpass and Train

### Expected behavior

I get this error when trying to open the latest version of overpass:

```
System.ArgumentException: Unable to map Overlay to a member of enum ObjectTypeFlags
   at ValveResourceFormat.Serialization.KVObjectExtensions.GetEnumValue[TEnum](KVObject collection, String name, Boolean normalize) in /_/ValveResourceFormat/Serialization/IKeyValueCollection.cs:line 165
   at GUI.Types.Renderer.WorldNodeLoader.Load(Scene scene) in /_/GUI/Types/Renderer/WorldNodeLoader.cs:line 47
   at GUI.Types.Renderer.WorldLoader.Load() in /_/GUI/Types/Renderer/WorldLoader.cs:line 103
   at GUI.Types.Renderer.WorldLoader..ctor(World world, Scene scene) in /_/GUI/Types/Renderer/WorldLoader.cs:line 52
   at GUI.Types.Renderer.GLWorldViewer.LoadScene() in /_/GUI/Types/Renderer/GLWorldViewer.cs:line 173
   at GUI.Types.Renderer.GLSceneViewer.OnLoad(Object sender, EventArgs e) in /_/GUI/Types/Renderer/GLSceneViewer.cs:line 296
   at GUI.Controls.GLViewerControl.OnLoad(Object sender, EventArgs e) in /_/GUI/Controls/GLViewerControl.cs:line 439
```

### Relevant log output or exception with stacktrace

```shell

```

### What game does this happen in

CS2

### Reference file in a Source 2 game

game/csgo/maps/de_overpass.vpk

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 560.70)

**Comment by xPaw** [comment]
Try dev build.
