### ISSUE TITLE
Extracting default models from CS2 leads to Unexpected v64 value for variable 'AdditionalFiles': 3 (0x3)

### ISSUE THREAD

**Issue by xLeviNx** [ValveResourceFormat/ValveResourceFormat#867]
### Describe the bug

Open pak01_dir.vpk and attempt to extract and decompile a vmat file from default game content. When attempting, it leads to the error in the title along with the log content pasted below. 

### Expected behavior

Open vmat, decompile and export content successfully. 

### Relevant log output or exception with stacktrace

```shell
[05:36:55.051] [ExtractProgressForm] Failed to extract 'flagkit_01_animated.vmat_c': ValveResourceFormat.Utils.UnexpectedMagicException: Unexpected v64 value for variable 'AdditionalFiles': 3 (0x3)
   at ValveResourceFormat.CompiledShader.FeaturesHeaderBlock..ctor(ShaderDataReader datareader) in /_/ValveResourceFormat/CompiledShader/Blocks/Headers/FeaturesHeaderBlock.cs:line 43
   at ValveResourceFormat.CompiledShader.ShaderFile.ParseFile() in /_/ValveResourceFormat/CompiledShader/ShaderFile.cs:line 120
   at ValveResourceFormat.CompiledShader.ShaderFile.Read(String filenamepath, Stream input) in /_/ValveResourceFormat/CompiledShader/ShaderFile.cs:line 101
   at ValveResourceFormat.IO.GameFileLoader.<LoadShaderFromDisk>g__TryLoadShader|20_0(VcsProgramType programType, VcsPlatformType platformType, VcsShaderModelType modelType, <>c__DisplayClass20_0&) in /_/ValveResourceFormat/IO/GameFileLoader.cs:line 232
   at ValveResourceFormat.IO.GameFileLoader.LoadShaderFromDisk(String shaderName) in /_/ValveResourceFormat/IO/GameFileLoader.cs:line 257
   at ValveResourceFormat.IO.GameFileLoader.LoadShader(String shaderName) in /_/ValveResourceFormat/IO/GameFileLoader.cs:line 290
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture_Internal(String textureType, Material material)
   at ValveResourceFormat.IO.ShaderDataProvider.GetInputsForTexture(String textureType, Material material) in /_/ValveResourceFormat/IO/ShaderDataProvider.cs:line 31
   at ValveResourceFormat.IO.MaterialExtract.GetTextureUnpackInfos(String textureType, String texturePath, Boolean omitDefaults, Boolean omitUniforms)+MoveNext() in /_/ValveResourceFormat/IO/MaterialExtract.cs:line 138
   at ValveResourceFormat.IO.MaterialExtract.ToValveMaterial() in /_/ValveResourceFormat/IO/MaterialExtract.cs:line 200
   at ValveResourceFormat.IO.MaterialExtract.ToContentFile() in /_/ValveResourceFormat/IO/MaterialExtract.cs:line 49
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader, IProgress`1 progress) in /_/ValveResourceFormat/IO/FileExtract.cs:line 174
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 406
```

### What game does this happen in

Counter-Strike 2

### Reference file in a Source 2 game

game/csgo/pak01_dir.vpk
models/generic/flagkit_01_animated.vmat_c

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 3060/PCIe/SSE2, Driver: 4.6.0 NVIDIA 566.14)

**Comment by xPaw** [comment]
Dev build fixed this already.
