### ISSUE TITLE
app crash when open any model

### ISSUE THREAD

**Issue by muk-as** [ValveResourceFormat/ValveResourceFormat#870]
### Describe the bug

10.1 ok
10.2 crash
11.0 crash

Windows 10.0.19045.4957

### Expected behavior

don't crash

### Relevant log output or exception with stacktrace

```shell
Application: Source2Viewer_10.2.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at GUI.Types.Renderer.PostProcessRenderer.Render(GUI.Types.Renderer.Framebuffer, Boolean)
   at GUI.Controls.GLViewerControl.FramebufferBlit(GUI.Types.Renderer.Framebuffer, GUI.Types.Renderer.Framebuffer, Boolean)
   at GUI.Controls.GLViewerControl.Draw()
   at OpenTK.GLControl.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.UserControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(System.Drawing.Rectangle, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSizeDockedControl(System.Windows.Forms.Layout.IArrangedElement, System.Drawing.Rectangle, Boolean, System.Drawing.Size ByRef, System.Drawing.Rectangle ByRef)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(System.Windows.Forms.Layout.IArrangedElement, Boolean)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSize(System.Windows.Forms.Layout.IArrangedElement, Boolean, System.Drawing.Size ByRef)
   at System.Windows.Forms.Control.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.ScrollableControl.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(System.Windows.Forms.Layout.IArrangedElement, System.String)
   at System.Windows.Forms.Control.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(System.Drawing.Rectangle, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSizeDockedControl(System.Windows.Forms.Layout.IArrangedElement, System.Drawing.Rectangle, Boolean, System.Drawing.Size ByRef, System.Drawing.Rectangle ByRef)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(System.Windows.Forms.Layout.IArrangedElement, Boolean)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSize(System.Windows.Forms.Layout.IArrangedElement, Boolean, System.Drawing.Size ByRef)
   at System.Windows.Forms.Control.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.ScrollableControl.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean)
   at System.Windows.Forms.SplitContainer.ResizeSplitContainer()
   at System.Windows.Forms.SplitContainer.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(System.Windows.Forms.Layout.IArrangedElement, System.String)
   at System.Windows.Forms.Control.OnResize(System.EventArgs)
   at System.Windows.Forms.ContainerControl.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ContainerControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.SplitContainer.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(System.Drawing.Rectangle, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSizeDockedControl(System.Windows.Forms.Layout.IArrangedElement, System.Drawing.Rectangle, Boolean, System.Drawing.Size ByRef, System.Drawing.Rectangle ByRef)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(System.Windows.Forms.Layout.IArrangedElement, Boolean)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSize(System.Windows.Forms.Layout.IArrangedElement, Boolean, System.Drawing.Size ByRef)
   at System.Windows.Forms.Control.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.ScrollableControl.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(System.Windows.Forms.Layout.IArrangedElement, System.String)
   at System.Windows.Forms.Control.OnResize(System.EventArgs)
   at System.Windows.Forms.UserControl.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.UserControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(System.Drawing.Rectangle, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSizeDockedControl(System.Windows.Forms.Layout.IArrangedElement, System.Drawing.Rectangle, Boolean, System.Drawing.Size ByRef, System.Drawing.Rectangle ByRef)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(System.Windows.Forms.Layout.IArrangedElement, Boolean)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSize(System.Windows.Forms.Layout.IArrangedElement, Boolean, System.Drawing.Size ByRef)
   at System.Windows.Forms.Control.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.ScrollableControl.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(System.Windows.Forms.Layout.IArrangedElement, System.String)
   at System.Windows.Forms.Control.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.TabPage.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.SetBounds(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.set_Bounds(System.Drawing.Rectangle)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.TabControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at Windows.Win32.PInvoke.<SetWindowPos>g__LocalExternFunction|10989_0(Windows.Win32.Foundation.HWND, Windows.Win32.Foundation.HWND, Int32, Int32, Int32, Int32, Windows.Win32.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(System.Drawing.Rectangle, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSizeDockedControl(System.Windows.Forms.Layout.IArrangedElement, System.Drawing.Rectangle, Boolean, System.Drawing.Size ByRef, System.Drawing.Rectangle ByRef)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(System.Windows.Forms.Layout.IArrangedElement, Boolean)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSize(System.Windows.Forms.Layout.IArrangedElement, Boolean, System.Drawing.Size ByRef)
   at System.Windows.Forms.Control.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.ScrollableControl.OnLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean)
   at GUI.MainForm+<>c__DisplayClass52_0.<OpenFile>b__3(System.Threading.Tasks.Task`1<System.Windows.Forms.TabPage>)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.SynchronizationContextTaskScheduler+<>c.<.cctor>b__8_0(System.Object)
   at DynamicClass.InvokeStub_SendOrPostCallback.Invoke(System.Object, System.Span`1<System.Object>)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
   at System.Windows.Forms.Application+ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr, Microsoft.Office.msoloop, Void*)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Microsoft.Office.msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Microsoft.Office.msoloop, System.Windows.Forms.ApplicationContext)
   at GUI.Program.Main(System.String[])
```

### What game does this happen in

DOTA2

### Reference file in a Source 2 game

any model
example, models/courier/baby_rosh/babyroshan.vmdl_c

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

Source 2 Viewer v11.0.3962+1ee504a175adc6c0bfdc7ffd20c3aa53f028a577

**Comment by muk-as** [comment]
fixed https://github.com/ValveResourceFormat/ValveResourceFormat/commit/9f6981eac52442192bdaf5123d02a6a67007fad7
