### ISSUE TITLE
VBIB remap table overflow

### ISSUE THREAD

**Issue by techsideofficial** [ValveResourceFormat/ValveResourceFormat#871]
### Describe the bug

When exporting a workshop item from SteamVR and trying to convert it to glTF, the program shows an error and stops exporting.

### Expected behavior

Map Should export correctly to glTF.

### Relevant log output or exception with stacktrace

```shell
[16:55:29.941] System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ValveResourceFormat.ResourceTypes.Morph.GetFlexVertexData() in /_/ValveResourceFormat/Resource/ResourceTypes/Morph.cs:line 44
   at ValveResourceFormat.IO.GltfModelExporter.CreateGltfMesh(String meshName, Mesh vmesh, VBIB vbib, ModelRoot exportedModel, Boolean includeJoints, String skinMaterialPath) in /_/ValveResourceFormat/IO/GltfModelExporter.Mesh.cs:line 42
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, String name, Mesh mesh, VBIB vbib, Node[] joints, String skinMaterialPath, Entity entity) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 630
   at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, String skinName, Entity entity) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 541
   at ValveResourceFormat.IO.GltfModelExporter.LoadEntityMeshes(ModelRoot exportedModel, Scene scene, EntityLump entityLump) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 242
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 192
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 129
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 383
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in /_/GUI/Types/Exporter/ExportFile.cs:line 107
   --- End of inner exception stack trace ---
```

### What game does this happen in

SteamVR

### Reference file in a Source 2 game

C:\Program Files (x86)\Steam\steamapps\workshop\content\250820\2006661698\2006661698.vpk

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

10.2.3850 4f2f81e04a752675cb4c31ee6572d4c53e0bb321 on Microsoft Windows NT 10.0.22631.0 (GPU: NVIDIA GeForce RTX 2060/PCIe/SSE2, Driver: 4.6.0 NVIDIA 560.94)

**Comment by xPaw** [comment]
You haven't tested latest release, let alone latest dev build.

**Comment by techsideofficial** [comment]
@xPaw I just tried the latest release and dev build, same issue:

`[10:31:45.295] [167/308] Exporting texture: barrier_fence64_normal_tga_a7b510a5.vtex
[10:31:45.304] Creating mesh: alyx_scan_holo.alyx_scan_holo
[10:31:45.315] [168/331] Exporting texture: interior_plant_palm_001_normal_psd_87eb17c.vtex
[10:31:45.318] Loading material: materials/models/hologram_fx/alyx_scan_holo.vmat
[10:31:45.350] [1/0] Exporting texture: silverware_1_ao_tga_5714bd14_orm_4231063996.png
[10:31:45.366] System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ValveResourceFormat.ResourceTypes.Morph.GetFlexVertexData() in /_/ValveResourceFormat/Resource/ResourceTypes/Morph.cs:line 44
   at ValveResourceFormat.IO.GltfModelExporter.CreateGltfMesh(String meshName, Mesh vmesh, VBIB vbib, ModelRoot exportedModel, Boolean includeJoints, String skinMaterialPath) in /_/ValveResourceFormat/IO/GltfModelExporter.Mesh.cs:line 42
   at ValveResourceFormat.IO.GltfModelExporter.AddMeshNode(ModelRoot exportedModel, Scene scene, String name, Mesh mesh, VBIB vbib, Node[] joints, String skinMaterialPath, Entity entity) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 630
   at ValveResourceFormat.IO.GltfModelExporter.LoadModel(ModelRoot exportedModel, Scene scene, Model model, String name, Matrix4x4 transform, String skinName, Entity entity) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 541
   at ValveResourceFormat.IO.GltfModelExporter.LoadEntityMeshes(ModelRoot exportedModel, Scene scene, EntityLump entityLump) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 242
   at ValveResourceFormat.IO.GltfModelExporter.ExportToFile(String resourceName, String fileName, World world) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 192
   at ValveResourceFormat.IO.GltfModelExporter.Export(Resource resource, String targetPath, CancellationToken cancellationToken) in /_/ValveResourceFormat/IO/GltfModelExporter.cs:line 129
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 383
   at GUI.Types.Exporter.ExportFile.<>c__DisplayClass1_1.<<ExtractFileFromStream>b__1>d.MoveNext() in /_/GUI/Types/Exporter/ExportFile.cs:line 107
   --- End of inner exception stack trace ---
[10:31:45.369] [2/2] Exporting texture: pan_1_ao_tga_564c7de7_orm_3483624440.png`

**Comment by kristiker** [comment]
https://github.com/user-attachments/assets/bc27073f-9d4c-4c70-97e6-05241ad6db31

alyx_scan_holo.vmdl_c now exports fine to glb, so should be fixed

**Comment by kristiker** [comment]
Oh its SteamVR, then I hope the model file is the same as in Half-Life: Alyx.
