### ISSUE TITLE
Deadlock cannot read some vdata_c files - Invalid KV3 signature for variable 'magic'

### ISSUE THREAD

**Issue by hassayag** [ValveResourceFormat/ValveResourceFormat#872]
### Describe the bug

I am unable to view some `vdata_c` game files for Deadlock. Tested this on both on windows desktop app and CLI. 

### Expected behavior

Able to read `scripts/abilities.vdata_c` file

### Relevant log output or exception with stacktrace

```shell
ValveResourceFormat.Utils.UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 1263940357 (0x4B563305)
   at ValveResourceFormat.ResourceTypes.BinaryKV3.Read(BinaryReader reader, Resource resource) in /_/ValveResourceFormat/Resource/ResourceTypes/BinaryKV3.cs:line 78
   at ValveResourceFormat.Blocks.ResourceEditInfo2.Read(BinaryReader reader, Resource resource) in /_/ValveResourceFormat/Resource/Blocks/ResourceEditInfo2.cs:line 35
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 242
   at GUI.Types.Viewers.Resource.Create(VrfGuiContext vrfGuiContext, Stream stream, Boolean isPreview) in /_/GUI/Types/Viewers/Resource.cs:line 40
   at GUI.MainForm.ProcessFile(VrfGuiContext vrfGuiContext, PackageEntry entry, Boolean isPreview) in /_/GUI/MainForm.cs:line 736
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

### What game does this happen in

Deadlock

### Reference file in a Source 2 game

`steamapps\common\Deadlock\game\citadel\pak01_dir.vpk > scripts/abilities.vdata_c`

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

11.0.3965 facd407de5fd5d7a684b649cbbc1e550a17fb0ba on Microsoft Windows NT 10.0.26100.0 (GPU: AMD Radeon RX 6800 XT, Driver: 4.6.0 Compatibility Profile Context 24.10.27.01.240827)

**Comment by notfrying1pans** [comment]
This happens in every new/modified asset as of today's deadlock update, not just vdata_c files. I've encountered it when trying to look at vmdl_c and vmat files too

**Comment by roserens** [comment]
Same here for Deadlock files. Any solution would be greatly appreciated. 

`
[archive index: 015] panorama\styles\unit_status_icons.vcss_c
File: panorama\styles\unit_status_icons.vcss_c (parent: C:\Program Files (x86)\Steam\steamapps\common\Deadlock\game\citadel\pak01_dir.vpk)
ValveResourceFormat.Utils.UnexpectedMagicException: Invalid KV3 signature for variable 'magic': 1263940357 (0x4B563305)
   at ValveResourceFormat.ResourceTypes.BinaryKV3.Read(BinaryReader reader, Resource resource) in /_/ValveResourceFormat/Resource/ResourceTypes/BinaryKV3.cs:line 78
   at ValveResourceFormat.Blocks.ResourceEditInfo2.Read(BinaryReader reader, Resource resource) in /_/ValveResourceFormat/Resource/Blocks/ResourceEditInfo2.cs:line 35
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 242
   at Decompiler.Decompiler.ProcessVPKEntries(String parentPath, Package package, IFileLoader fileLoader, String type, Dictionary`2 manifestData) in /_/Decompiler/Decompiler.cs:line 1038
`

![Image](https://github.com/user-attachments/assets/59603de1-94e8-43ca-bd31-e7324bb2d234)
