### ISSUE TITLE
Decompile Failed to extract File size (3542)

### ISSUE THREAD

**Issue by SpsZaPIZZA** [ValveResourceFormat/ValveResourceFormat#883]
### Describe the bug

HI, when decompiling the map, there are errors with some materials and with the vmap itself

### Expected behavior

full decompilation

### Relevant log output or exception with stacktrace

```shell
[19:52:29.160] [ExtractProgressForm] Failed to extract 'maps/sandstone_snow_resand/worldnodes/node000_world_lr0_agg172_1_usps_noir.vmdl_c': System.IO.InvalidDataException: File size (3542) does not match size specified in file (3526) (Material).
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 317
   at ValveResourceFormat.IO.GameFileLoader.LoadFile(String file) in /_/ValveResourceFormat/IO/GameFileLoader.cs:line 343
   at ValveResourceFormat.IO.ModelExtract.GrabMaterialInputSignatures(Resource resource) in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 118
   at ValveResourceFormat.IO.ModelExtract.EnqueueRenderMeshes() in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 88
   at ValveResourceFormat.IO.ModelExtract..ctor(Resource modelResource, IFileLoader fileLoader) in /_/ValveResourceFormat/IO/ModelExtract.cs:line 53
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader, IProgress`1 progress) in /_/ValveResourceFormat/IO/FileExtract.cs:line 136
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 418
---------------------------------------------------------------------------------------------------------------
 [ExtractProgressForm] Failed to extract 'maps/sandstone_snow_resand/world.vwrld_c': System.IO.InvalidDataException: File size (3542) does not match size specified in file (3526) (Material).
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 317
   at ValveResourceFormat.IO.GameFileLoader.LoadFile(String file) in /_/ValveResourceFormat/IO/GameFileLoader.cs:line 343
   at ValveResourceFormat.IO.ModelExtract.GrabMaterialInputSignatures(Resource resource) in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 118
   at ValveResourceFormat.IO.ModelExtract.EnqueueRenderMeshes() in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 88
   at ValveResourceFormat.IO.ModelExtract..ctor(Resource modelResource, IFileLoader fileLoader) in /_/ValveResourceFormat/IO/ModelExtract.cs:line 53
   at ValveResourceFormat.IO.ModelExtract.GetContentFiles_DrawCallSplit(Resource aggregateModelResource, IFileLoader fileLoader, Vector3[] drawOrigins, Int32 drawCallCount)+MoveNext() in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 192
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ValveResourceFormat.IO.MapExtract.<HandleWorldNode>g__ProcessAggregate|94_6(KVObject agg, Int32 layerIndex, List`1 layerNodes) in /_/ValveResourceFormat/IO/MapExtract.cs:line 774
   at ValveResourceFormat.IO.MapExtract.HandleWorldNode(WorldNode node) in /_/ValveResourceFormat/IO/MapExtract.cs:line 880
   at ValveResourceFormat.IO.MapExtract.ToValveMap() in /_/ValveResourceFormat/IO/MapExtract.cs:line 305
   at ValveResourceFormat.IO.MapExtract.ToContentFile() in /_/ValveResourceFormat/IO/MapExtract.cs:line 217
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader, IProgress`1 progress) in /_/ValveResourceFormat/IO/FileExtract.cs:line 132
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 418
--------------------------------------------------------------------------------------------
[19:52:22.472] [ExtractProgressForm] Failed to extract 'maps/sandstone_snow_resand.vmap_c': System.IO.InvalidDataException: File size (3542) does not match size specified in file (3526) (Material).
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 317
   at ValveResourceFormat.IO.GameFileLoader.LoadFile(String file) in /_/ValveResourceFormat/IO/GameFileLoader.cs:line 343
   at ValveResourceFormat.IO.ModelExtract.GrabMaterialInputSignatures(Resource resource) in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 118
   at ValveResourceFormat.IO.ModelExtract.EnqueueRenderMeshes() in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 88
   at ValveResourceFormat.IO.ModelExtract..ctor(Resource modelResource, IFileLoader fileLoader) in /_/ValveResourceFormat/IO/ModelExtract.cs:line 53
   at ValveResourceFormat.IO.ModelExtract.GetContentFiles_DrawCallSplit(Resource aggregateModelResource, IFileLoader fileLoader, Vector3[] drawOrigins, Int32 drawCallCount)+MoveNext() in /_/ValveResourceFormat/IO/ModelExtract.Mesh.cs:line 192
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ValveResourceFormat.IO.MapExtract.<HandleWorldNode>g__ProcessAggregate|94_6(KVObject agg, Int32 layerIndex, List`1 layerNodes) in /_/ValveResourceFormat/IO/MapExtract.cs:line 774
   at ValveResourceFormat.IO.MapExtract.HandleWorldNode(WorldNode node) in /_/ValveResourceFormat/IO/MapExtract.cs:line 880
   at ValveResourceFormat.IO.MapExtract.ToValveMap() in /_/ValveResourceFormat/IO/MapExtract.cs:line 305
   at ValveResourceFormat.IO.MapExtract.ToContentFile() in /_/ValveResourceFormat/IO/MapExtract.cs:line 217
   at ValveResourceFormat.IO.FileExtract.Extract(Resource resource, IFileLoader fileLoader, IProgress`1 progress) in /_/ValveResourceFormat/IO/FileExtract.cs:line 132
   at GUI.Forms.ExtractProgressForm.ExtractFile(Resource resource, String inFilePath, String outFilePath, Boolean flatSubfiles) in /_/GUI/Forms/ExtractProgressForm.cs:line 418
```

### What game does this happen in

CS2

### Reference file in a Source 2 game

https://steamcommunity.com/sharedfiles/filedetails/?id=3391719302

### Have you tried the latest dev build?

Yes

### What version of VRF are you using?

11.1.4053 a78b6cd1d8942c50c5bd70db505652c34a384dda on Microsoft Windows NT 10.0.19045.0 (GPU: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2, Driver: 4.6.0 NVIDIA 566.14)

**Comment by xPaw** [comment]
If the size doesn't match then the file is corrupted (intentionally or not), in this case it has extra data it shouldn't. I doubt Source 2 tooling producing this file like this.

**Comment by SpsZaPIZZA** [comment]
The file is not corrupted, it works fine in cs2 and runs as a map, you can check it yourself. the link I provided. I can also record a video if you need to

**Comment by Angel-foxxo** [comment]
Source2 might run it just because of extra safeguards it has in place but I checked and some of the files are definitely messed with in some shape or form, if this is specifically anti-decompile protection I can't tell but its not worth it to spend time optimising for every misshapen file out there, Source2 tools would never produce something like this.
